// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtlLtoO8jKS1Zco01VKiFkFCBW7QxTmMo',
    appId: '1:507734879692:web:12b6c1743ee999b2380169',
    messagingSenderId: '507734879692',
    projectId: 'mercanova-delivery',
    authDomain: 'mercanova-delivery.firebaseapp.com',
    storageBucket: 'mercanova-delivery.firebasestorage.app',
    measurementId: 'G-XGQ3XBY067',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHkonjWAYviw46p1bYfaNZ6faGvVcgVSo',
    appId: '1:507734879692:android:5fd3f7090ee6a858380169',
    messagingSenderId: '507734879692',
    projectId: 'mercanova-delivery',
    storageBucket: 'mercanova-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh62rmPppEbpiiPamwa29WQd69DiZvQQ0',
    appId: '1:507734879692:ios:cc29569b8d1d1c98380169',
    messagingSenderId: '507734879692',
    projectId: 'mercanova-delivery',
    storageBucket: 'mercanova-delivery.firebasestorage.app',
    iosClientId: '507734879692-4mv9hbebohgcsj0sb5ktd7csa745vojv.apps.googleusercontent.com',
    iosBundleId: 'com.example.novapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh62rmPppEbpiiPamwa29WQd69DiZvQQ0',
    appId: '1:507734879692:ios:cc29569b8d1d1c98380169',
    messagingSenderId: '507734879692',
    projectId: 'mercanova-delivery',
    storageBucket: 'mercanova-delivery.firebasestorage.app',
    iosClientId: '507734879692-4mv9hbebohgcsj0sb5ktd7csa745vojv.apps.googleusercontent.com',
    iosBundleId: 'com.example.novapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtlLtoO8jKS1Zco01VKiFkFCBW7QxTmMo',
    appId: '1:507734879692:web:a9a1eaa2c60e72e5380169',
    messagingSenderId: '507734879692',
    projectId: 'mercanova-delivery',
    authDomain: 'mercanova-delivery.firebaseapp.com',
    storageBucket: 'mercanova-delivery.firebasestorage.app',
    measurementId: 'G-EXT3EK3VD9',
  );
}
